<a href="https://colab.research.google.com/github/intelligent-environments-lab/CityLearn/blob/master/examples/quickstart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# QuickStart

Install the latest CityLearn version from PyPi with the :code:`pip` command:

In [ ]:
pip install CityLearn==2.0.0

In [16]:
from citylearn.agents.marlisa import MARLISA as RLAgent
from citylearn.citylearn import CityLearnEnv, EvaluationCondition

dataset_name = 'citylearn_challenge_2022_phase_1'
env = CityLearnEnv(dataset_name, central_agent=False, simulation_end_time_step=1000)
model = RLAgent(env)
model.learn(episodes=1, deterministic_finish=False)

# print cost functions at the end of episode
kpis = model.env.evaluate(baseline_condition=EvaluationCondition.WITHOUT_STORAGE_BUT_WITH_PARTIAL_LOAD_AND_PV)
kpis = kpis.pivot(index='cost_function', columns='name', values='value')
kpis = kpis.dropna(how='all')
display(kpis)

name,Building_1,Building_2,Building_3,Building_4,Building_5,District
cost_function,,,,,,
annual_peak_average,NaN,NaN,NaN,NaN,NaN,1.447566
carbon_emissions_total,1.193323,1.350958,1.323591,1.480461,1.455220,1.360711
cost_total,1.182906,1.330226,1.295928,1.539299,1.350830,1.339838
daily_one_minus_load_factor_average,NaN,NaN,NaN,NaN,NaN,1.018450
daily_peak_average,NaN,NaN,NaN,NaN,NaN,1.261681
discomfort_delta_average,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
discomfort_delta_maximum,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
discomfort_delta_minimum,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
electricity_consumption_total,1.195282,1.374369,1.315540,1.455859,1.488817,1.365973
monthly_one_minus_load_factor_average,NaN,NaN,NaN,NaN,NaN,1.018073
ramping_average,NaN,NaN,NaN,NaN,NaN,2.000872
zero_net_energy,1.123510,1.181045,1.176495,1.191527,1.203078,1.175131

In [17]:
model.learn(episodes=5, deterministic_finish=False)

kpis = model.env.evaluate(baseline_condition=EvaluationCondition.WITHOUT_STORAGE_BUT_WITH_PARTIAL_LOAD_AND_PV)
kpis = kpis.pivot(index='cost_function', columns='name', values='value')
kpis = kpis.dropna(how='all')
display(kpis)

name,Building_1,Building_2,Building_3,Building_4,Building_5,District
cost_function,,,,,,
annual_peak_average,NaN,NaN,NaN,NaN,NaN,1.090995
carbon_emissions_total,1.015497,0.929255,1.036805,1.118417,1.042944,1.028584
cost_total,0.955732,0.872519,1.005924,1.094143,0.998596,0.985383
daily_one_minus_load_factor_average,NaN,NaN,NaN,NaN,NaN,0.970659
daily_peak_average,NaN,NaN,NaN,NaN,NaN,0.979552
discomfort_delta_average,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
discomfort_delta_maximum,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
discomfort_delta_minimum,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
electricity_consumption_total,1.019103,0.933523,1.030493,1.117731,1.040136,1.028197
monthly_one_minus_load_factor_average,NaN,NaN,NaN,NaN,NaN,0.994238
ramping_average,NaN,NaN,NaN,NaN,NaN,1.174641
zero_net_energy,1.060796,1.047369,1.052831,1.065333,1.076296,1.060525